# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# 网站
title: 就像風住了風又起 #标题
subtitle: '' #副标题
description: 這樣看你，用所有的眼睛和所有的距離，就像風住了風又起 #描述
keywords: Blog #关键词，支持多个关键词
author: 就像風住了風又起
language: zh-TW
timezone: '' #时区，默认设备时区

# URL
# 网址, 必须以 http:// 或 https:// 开头
url: http://blog.s12day.dpdns.org
# 文章的永久链接格式
permalink: :year/:month/:day/:title/
# 永久链接中各部分的默认值
permalink_defaults:
pretty_urls:
  # 是否在永久链接中保留尾部的index.html，默认为true，设置为false时去除
  trailing_index: true
  # 是否在永久链接中保留尾部的.html，默认为true，设置为false时去除 (对尾部的index.html无效)
  trailing_html: true

# 目录
# Source文件夹存储内容的位置
source_dir: source
# Pubic文件夹生成静态站点的位置
public_dir: public
# 标签文件夹
tag_dir: tags
# 归档文件夹
archive_dir: archives
# 分类文件夹
category_dir: categories
# Include code文件夹，source_dir下的子目录
code_dir: downloads/code
# 国际化（i18n）文件夹
i18n_dir: :lang
# 匹配到的文件将会被不做改动地复制到public目录中。您可使用glob表达式来匹配路径。
skip_render:

# 文章
# 新文章的文件名称
new_post_name: :title.md
# 预设布局
default_layout: post
# 把标题转换为title case
titlecase: false
# 在新标签中打开链接
external_link:
  enable: true
  # 对整个网站（site）生效或仅对文章（post）生效
  field: site
  # 需要排除的域名。 主域名和子域名如 www 需分别配置
  exclude: ''
# 设置为 1 ，将文件名转换为小写形式； 设置为 2 ，将文件名转换为大写形式
filename_case: 0
# 显示草稿
render_drafts: false
# 启用资源文件夹
post_asset_folder: false
# 把链接改为与根目录的相对地址
relative_link: false
# 显示未来的文章
future: true
# 代码块的设置, 请参考https://hexo.io/zh-cn/docs/syntax-highlight进行设置
syntax_highlighter: highlight.js
# 代码块的设置, 请参考https://hexo.io/zh-cn/docs/syntax-highlight#Highlight-js进行设置
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
# 代码块的设置, 请参考https://hexo.io/zh-cn/docs/syntax-highlight#PrismJS进行设置
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# 首页设置
# 生成帖子归档。由 hexo-generator-index 驱动
index_generator:
  # 博客索引页面的根路径
  path: ''
  # 每页显示帖子数
  per_page: 10
  # 默认情况下按日期降序(从新到旧)
  order_by: -date

# 默认分类
default_category: uncategorized
# 分类别名
category_map:
# 标签别名
tag_map:

meta_generator: true

# 日期格式
date_format: YYYY-MM-DD
# 时间格式
time_format: HH:mm:ss
# 当Front Matter中没有指定updated时updated的取值
updated_option: 'mtime'

# 每页显示的帖子数。 0 关闭分页功能
per_page: 10
# URL format
pagination_dir: page

# include 和 exclude 选项只会应用到 source/
# 而 ignore 选项会应用到所有文件夹
# 包含隐藏文件（包括名称以下划线开头的文件/文件夹，* 除外）
include:
# 排除文件或文件夹
exclude:
# 忽略文件/文件夹
ignore:

# 拓展
# 插件: https://hexo.io/plugins/


# 主题: https://hexo.io/themes/
theme: butterfly

# 部署
# 文档: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:S12day00/Blog.git
  branch: hexo